---
# =============================================================================
# Kibana Default Variables - Version 9.3.2
# =============================================================================

# Server settings
kibana_server_host: 0.0.0.0
kibana_server_port: 5601
kibana_server_name: "kibana"

# Elasticsearch connection (private IP from inventory!)
elasticsearch_hosts:
  - "http://{{ hostvars['elasticsearch']['ansible_host'] }}:9200"
