---

# ------------------------ Server Settings -------------------
kibana_server_host: 0.0.0.0
kibana_server_port: 5601
kibana_server_name: "kibana"

# ------------------------ Logging Settings ------------------
kibana_log_level: info
kibana_log_file: /var/log/kibana/kibana.log

# ------------------------ Telemetry -------------------------
kibana_telemetry_enabled: false
kibana_telemetry_optin: false