---
# =============================================================================
# FILEBEAT DEFAULT VARIABLES
# =============================================================================

# -----------------------------------------------------------------------------
# Filebeat Version & Installation
# -----------------------------------------------------------------------------
filebeat_version: "9.3.2"
filebeat_package_state: present

# -----------------------------------------------------------------------------
# Index Settings
# -----------------------------------------------------------------------------
filebeat_ilm_enabled: false
filebeat_template_enabled: false
filebeat_template_name: "filebeat"
filebeat_template_pattern: "filebeat-*"

# -----------------------------------------------------------------------------
# Logging Settings
# -----------------------------------------------------------------------------
filebeat_log_level: warning
filebeat_log_path: /var/log/filebeat
filebeat_log_filename: filebeat
filebeat_log_keepfiles: 7

# -----------------------------------------------------------------------------
# Service Settings
# -----------------------------------------------------------------------------
filebeat_service_enabled: yes
filebeat_service_state: started

# -----------------------------------------------------------------------------
# Processors
# -----------------------------------------------------------------------------
filebeat_add_host_meta: true
filebeat_add_cloud_meta: true

# -----------------------------------------------------------------------------
# Filebeat Package
# -----------------------------------------------------------------------------
filebeat_package: "filebeat-9.3.2-amd64.deb"