---
prometheus_version: "3.1.0"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_log_dir: /var/log/prometheus
prometheus_port: 9090
nginx_exporter_port: 9113
prometheus_listen_address: "0.0.0.0"
prometheus_retention_time: "15d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"