---

- name: Restart Filebeat
  systemd:
    name: filebeat
    state: restarted
    daemon_reload: yes

- name: Reload Filebeat
  systemd:
    name: filebeat
    state: reloaded
    daemon_reload: no