---
# Kibana Setup Defaults

kibana_data_views:
  - id: "applogs-*"
    title: "applogs-*"
    time_field: "@timestamp"

kibana_api_url: "http://127.0.0.1:5601"
kibana_api_retries: 15
kibana_api_delay: 10
kibana_default_data_view: "applogs-*"